env:
  browser: true
  es2021: true
  
extends:
  - airbnb-base
  - plugin:react/recommended

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 13
  sourceType: module
  
plugins:
  - react

rules:
  no-console: 0
  import/extensions: 
    - error
    - ignorePackages
    - js: always
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
